name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: moodle
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            moodle-branch: MOODLE_500_STABLE
            database: mariadb
            suite: classic
            profile: default
          - php: 8.3
            moodle-branch: MOODLE_500_STABLE
            database: pgsql
            suite: default
            profile: chrome
    steps:
      - name: Check out plugin code
        uses: actions/checkout@v4
        with:
          path: ./mod/surveypro

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=5000
          coverage: pcov

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: moodle-plugin-ci install --plugin ./mod/surveypro --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint ./mod/surveypro

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd ./mod/surveypro

      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker ./mod/surveypro

      - name: Moodle PHPDoc Checker
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc ./mod/surveypro

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate ./mod/surveypro

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints ./mod/surveypro

      - name: Mustache Lint
        if: ${{ always() }}
        run: moodle-plugin-ci mustache ./mod/surveypro

      - name: Grunt
        if: ${{ always() }}
        run: moodle-plugin-ci grunt ./mod/surveypro

      - name: PHPUnit tests
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit --coverage-text ./mod/surveypro

      - name: Behat features
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile ${{ matrix.profile }} --suite ${{ matrix.suite }}
